In [ ]:
!pip install -q keras

### **1. Import Necessary Libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### **2. Import Dataset**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv

In [ ]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [ ]:
df.describe()

         RowNumber    CustomerId  ...  EstimatedSalary        Exited
count  10000.00000  1.000000e+04  ...     10000.000000  10000.000000
mean    5000.50000  1.569094e+07  ...    100090.239881      0.203700
std     2886.89568  7.193619e+04  ...     57510.492818      0.402769
min        1.00000  1.556570e+07  ...        11.580000      0.000000
25%     2500.75000  1.562853e+07  ...     51002.110000      0.000000
50%     5000.50000  1.569074e+07  ...    100193.915000      0.000000
75%     7500.25000  1.575323e+07  ...    149388.247500      0.000000
max    10000.00000  1.581569e+07  ...    199992.480000      1.000000

[8 rows x 11 columns]

**Conclusion -**
1. Dataset Shape - (10000, 14)
2. Numerical features - 11
3. Categorical features - 3
4. Null Values - 0

### **3. Data Preprocessing**

#### **3.1. Label Encoding**

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

In [ ]:
df['Geography'] = lb.fit_transform(df['Geography'])
df['Gender'] = lb.fit_transform(df['Gender'])

In [ ]:
df

      RowNumber  CustomerId    Surname  ...  IsActiveMember  EstimatedSalary  Exited
0             1    15634602   Hargrave  ...               1        101348.88       1
1             2    15647311       Hill  ...               1        112542.58       0
2             3    15619304       Onio  ...               0        113931.57       1
3             4    15701354       Boni  ...               0         93826.63       0
4             5    15737888   Mitchell  ...               1         79084.10       0
...         ...         ...        ...  ...             ...              ...     ...
9995       9996    15606229   Obijiaku  ...               0         96270.64       0
9996       9997    15569892  Johnstone  ...               1        101699.77       0
9997       9998    15584532        Liu  ...               1         42085.58       1
9998       9999    15682355  Sabbatini  ...               0         92888.52       1
9999      10000    15628319     Walker  ...               0         38190.78       0

[10000 rows x 14 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  int64
 5   Gender           10000 non-null  int64
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(11), object(1)
memory usage: 1.1+ MB

#### **3.2. Feature Selection**

In [ ]:
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [ ]:
df.shape

(10000, 11)

#### **3.3. Train Test Split**

In [ ]:
y = df.pop('Exited')
X = df

In [ ]:
X.shape

(10000, 10)

In [ ]:
y.shape

(10000,)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#### **3.4. Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
X_train

array([[ 0.16958176,  1.51919821, -1.09168714, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-2.30455945,  0.3131264 ,  0.91601335, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-1.19119591, -0.89294542, -1.09168714, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.9015152 , -0.89294542,  0.91601335, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.62420521,  1.51919821, -1.09168714, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-0.28401079,  0.3131264 , -1.09168714, ...,  0.64259497,
        -1.03227043,  0.32472465]])

### **4. Model Building**

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU, PReLU, ELU
from keras.layers import Dropout

#initialize the ANN
classifier = Sequential()

# Add the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'he_uniform',activation='relu',input_dim = 10))

# Add the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'he_uniform',activation='relu'))

# Add the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'glorot_uniform', activation = 'sigmoid'))

# Compile the ANN
classifier.compile(optimizer = 'Adamax', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
model_history=classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

# list all data in history
classifier.summary()
#total params are total number of weights and biases

Epoch 1/100
800/800 [==============================] - 14s 1ms/step - loss: 0.6171 - accuracy: 0.7020
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 0.5117 - accuracy: 0.7917
Epoch 3/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4891 - accuracy: 0.7918
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4755 - accuracy: 0.7948
Epoch 5/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4691 - accuracy: 0.7957
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4574 - accuracy: 0.7956
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4453 - accuracy: 0.7997
Epoch 8/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4444 - accuracy: 0.7941
Epoch 9/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4340 - accuracy: 0.8001
Epoch 10/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4335 - accuracy: 0.7952
Epoch 11/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4428 - accuracy: 0.7876
Epoch 12/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4336 - accuracy: 0.7928
Epoch 13/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4293 - accuracy: 0.7966
Epoch 14/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4184 - accuracy: 0.8028
Epoch 15/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4200 - accuracy: 0.8003
Epoch 16/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4205 - accuracy: 0.7955
Epoch 17/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4154 - accuracy: 0.8022
Epoch 18/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4087 - accuracy: 0.8000
Epoch 19/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4128 - accuracy: 0.8060
Epoch 20/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3980 - accuracy: 0.8081
Epoch 21/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4096 - accuracy: 0.8000
Epoch 22/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3972 - accuracy: 0.8103
Epoch 23/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3878 - accuracy: 0.8139
Epoch 24/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3873 - accuracy: 0.8200
Epoch 25/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3911 - accuracy: 0.8255
Epoch 26/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3884 - accuracy: 0.8228
Epoch 27/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3910 - accuracy: 0.8251
Epoch 28/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3851 - accuracy: 0.8294
Epoch 29/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3754 - accuracy: 0.8376
Epoch 30/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3886 - accuracy: 0.8281
Epoch 31/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3849 - accuracy: 0.8307
Epoch 32/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3781 - accuracy: 0.8331
Epoch 33/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3830 - accuracy: 0.8300
Epoch 34/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3757 - accuracy: 0.8347
Epoch 35/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3678 - accuracy: 0.8387
Epoch 36/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3662 - accuracy: 0.8427
Epoch 37/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3711 - accuracy: 0.8421
Epoch 38/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3699 - accuracy: 0.8471
Epoch 39/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3911 - accuracy: 0.8326
Epoch 40/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3719 - accuracy: 0.8453
Epoch 41/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3590 - accuracy: 0.8502
Epoch 42/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3684 - accuracy: 0.8452
Epoch 43/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3663 - accuracy: 0.8488
Epoch 44/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3655 - accuracy: 0.8498
Epoch 45/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3683 - accuracy: 0.8462
Epoch 46/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3683 - accuracy: 0.8493
Epoch 47/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3593 - accuracy: 0.8507
Epoch 48/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3646 - accuracy: 0.8495
Epoch 49/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3635 - accuracy: 0.8498
Epoch 50/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3551 - accuracy: 0.8553
Epoch 51/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3588 - accuracy: 0.8497
Epoch 52/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3603 - accuracy: 0.8550
Epoch 53/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3523 - accuracy: 0.8534
Epoch 54/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3529 - accuracy: 0.8590
Epoch 55/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3619 - accuracy: 0.8512
Epoch 56/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3527 - accuracy: 0.8584
Epoch 57/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3566 - accuracy: 0.8563
Epoch 58/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3483 - accuracy: 0.8576
Epoch 59/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3529 - accuracy: 0.8558
Epoch 60/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3507 - accuracy: 0.8589
Epoch 61/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3586 - accuracy: 0.8538
Epoch 62/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3407 - accuracy: 0.8652
Epoch 63/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3509 - accuracy: 0.8515
Epoch 64/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3479 - accuracy: 0.8563
Epoch 65/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3602 - accuracy: 0.8555
Epoch 66/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3469 - accuracy: 0.8541
Epoch 67/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3539 - accuracy: 0.8568
Epoch 68/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3433 - accuracy: 0.8624
Epoch 69/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3494 - accuracy: 0.8591
Epoch 70/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3354 - accuracy: 0.8671
Epoch 71/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3443 - accuracy: 0.8574
Epoch 72/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3388 - accuracy: 0.8661
Epoch 73/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3505 - accuracy: 0.8550
Epoch 74/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3480 - accuracy: 0.8594
Epoch 75/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3538 - accuracy: 0.8567
Epoch 76/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3488 - accuracy: 0.8595
Epoch 77/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3441 - accuracy: 0.8586
Epoch 78/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3443 - accuracy: 0.8600
Epoch 79/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3529 - accuracy: 0.8568
Epoch 80/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3447 - accuracy: 0.8624
Epoch 81/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3509 - accuracy: 0.8622
Epoch 82/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3452 - accuracy: 0.8564
Epoch 83/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3373 - accuracy: 0.8668
Epoch 84/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3491 - accuracy: 0.8552
Epoch 85/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3465 - accuracy: 0.8573
Epoch 86/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3410 - accuracy: 0.8610
Epoch 87/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3356 - accuracy: 0.8678
Epoch 88/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3480 - accuracy: 0.8580
Epoch 89/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3388 - accuracy: 0.8674
Epoch 90/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3430 - accuracy: 0.8612
Epoch 91/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3395 - accuracy: 0.8622
Epoch 92/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3439 - accuracy: 0.8614
Epoch 93/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3518 - accuracy: 0.8529
Epoch 94/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3512 - accuracy: 0.8536
Epoch 95/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3547 - accuracy: 0.8525
Epoch 96/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3336 - accuracy: 0.8653
Epoch 97/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3433 - accuracy: 0.8539
Epoch 98/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3385 - accuracy: 0.8663
Epoch 99/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3466 - accuracy: 0.8623
Epoch 100/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3378 - accuracy: 0.8648
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 6)                 66
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 42
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7
=================================================================
Total params: 115
Trainable params: 115
Non-trainable params: 0
_________________________________________________________________

### **5. Model Evaluation**

In [ ]:
# Predict the Test set results
Y_pred = classifier.predict(X_test)
Y_pred

array([[0.24071875],
       [0.31331962],
       [0.22490042],
       ...,
       [0.15479413],
       [0.13188156],
       [0.17853644]], dtype=float32)

In [ ]:
Y_pred = (Y_pred > 0.5)

In [ ]:
Y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, Y_pred)
print(cm)

[[1533   62]
 [ 213  192]]

In [ ]:
# Calculate the Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(Y_pred,y_test)

In [ ]:
print(score)

0.8625